#PORT
#server.port=8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcoursecluster.tko9sqd.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority

